version: '3'
services:
  database_1:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - flaskapidb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: flaskapi
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_DB: flaskapi
      TZ: America/Sao_Paulo
volumes:
  flaskapidb:
